import os

GREENHOUSE_ID_ENV_VAR = "GREENHOUSE_ID"
GREENHOUSE_ID = os.getenv(GREENHOUSE_ID_ENV_VAR, "A")
BLOCK_ID_ENV_VAR = "BLOCK_ID"
BLOCK_ID = os.getenv(BLOCK_ID_ENV_VAR, "1")
LOCAL_PORT_ENV_VAR = "LOCAL_PORT"
DT_PORT = int(os.getenv(LOCAL_PORT_ENV_VAR))
SENSOR_LOGS_TIMESTAMP_COLUMN = "timestamp"
STORAGE_TIME_PERIOD_DAYS = 1
SENSOR_LOGS_COLUMNS = list(["values", SENSOR_LOGS_TIMESTAMP_COLUMN])
GH_BLOCK_METADATA = {"DT:GH_block", "greenhouse:" + str(GREENHOUSE_ID), "block:" + str(BLOCK_ID)}
GH_BLOCK_METADATA_DOCKER = {"DT:GH_block-DockerNet", "greenhouse:" + str(GREENHOUSE_ID), "block:" + str(BLOCK_ID)}
NETWORK_ID_METADATA_KEY = "network_id:"
CONTAINER_PORT_METADATA_KEY = "container_port:"
CONTAINER_PORT_ENV_VAR = "CONT_PORT"
HOST_IP_METADATA_KEY = "host_ip:"
HOST_IP_ENV_VAR = "HOST_IP"
ELECTION_INITIATION_DELAY_SECONDS = 3
ELECTION_CONTACT_RETRY_ATTEMPTS = 3
QUERY_FORWARDING_MAX_ATTEMPTS = 3
QUERY_FORWARDING_REDIRECTION_DELAY = 2
CACHE_LOGS_TTL_HOURS = 1
CACHE_LOGS_CLEANING_TIME_DELTA_MINUTES = 10
NAMESERVER_HOSTNAME = "NS_container"
