GREENHOUSE_ID = "A"
BLOCK_ID = "1"
SENSOR_LOGS_TIMESTAMP_COLUMN = "timestamp"
STORAGE_TIME_PERIOD_DAYS = 1
SENSOR_LOGS_COLUMNS = list(["values", SENSOR_LOGS_TIMESTAMP_COLUMN])
GH_BLOCK_METADATA = {"DT:GH_block", "greenhouse:" + str(GREENHOUSE_ID), "block:" + str(BLOCK_ID)}
NETWORK_ID_METADATA_KEY = "network_id:"
ELECTION_INITIATION_DELAY_SECONDS = 1
ELECTION_CONTACT_RETRY_ATTEMPTS = 3
QUERY_FORWARDING_MAX_ATTEMPTS = 3
QUERY_FORWARDING_REDIRECTION_DELAY = 2
CACHE_LOGS_TTL_HOURS = 1
CACHE_LOGS_CLEANING_TIME_DELTA_MINUTES = 10

