GET_LOGS_MAX_TRIES = 5
STREAM_DATA_COLUMNS = ["values", "timestamp"]
SENSOR_LOGS_TIMESTAMP_COLUMN = "timestamp"
GRAPH_ROLLOVER = 500
SENSOR_OPTIONS = [("AIRHUMIDITY", "Air humidity"), ("LUX", "Lux"), ("TEMPERATURE", "Temperature")]
BLOCK_ID_OPTIONS = [("A1", "A1"), ("A2", "A2"), ("B1", "B1"), ("B2", "B2")]
UPDATE_PERIOD = 30000  # UPDATE PERIOD IN MILLISECONDS
MIN_DELTA_BETWEEN_SAMPLES_SECS = 1
